version: '3.8'

services: 
  postgres: 
    container_name: nest-clean-pg
    image: bitnami/postgresql
    ports:
      - 5433:5432 
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=nest-clean